title: Muhammad Nabil Bin Saiful Amin
logo: /assets/img/WIN_20241015_13_48_24_Pro.jpg
description: Senior Lecturer | AI & Data Analytics in Energy | Smart Grid & Renewable Energy Solutions  
#show_downloads: true
theme: jekyll-theme-minimal
